dependencies = []
description = "This package is a wrapper around the data contained in `/proc/net/dev`. It returns structured data from this file."
flags = ["lib"]
languages = ["go", "github-actions"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.1.2"
